# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'faceView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_face_window(object):
    def setupUi(self, face_window):
        face_window.setObjectName("face_window")
        face_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(face_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 120, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_face = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_face.setGeometry(QtCore.QRect(140, 360, 93, 28))
        self.pushButton_face.setObjectName("pushButton_face")
        self.pushButton_check = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_check.setGeometry(QtCore.QRect(530, 360, 93, 28))
        self.pushButton_check.setObjectName("pushButton_check")
        face_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(face_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        face_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(face_window)
        self.statusbar.setObjectName("statusbar")
        face_window.setStatusBar(self.statusbar)

        self.retranslateUi(face_window)
        QtCore.QMetaObject.connectSlotsByName(face_window)

    def retranslateUi(self, face_window):
        _translate = QtCore.QCoreApplication.translate
        face_window.setWindowTitle(_translate("face_window", "MainWindow"))
        self.label.setText(_translate("face_window", "员工人脸检测"))
        self.pushButton_face.setText(_translate("face_window", "人脸识别"))
        self.pushButton_check.setText(_translate("face_window", "考勤打卡"))
