# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_ui(object):
    def setupUi(self, login_ui):
        login_ui.setObjectName("login_ui")
        login_ui.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(login_ui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 260, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 300, 51, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 260, 151, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 300, 151, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 450, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(550, 450, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 100, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 180, 141, 31))
        self.label_6.setObjectName("label_6")
        login_ui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login_ui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        login_ui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login_ui)
        self.statusbar.setObjectName("statusbar")
        login_ui.setStatusBar(self.statusbar)

        self.retranslateUi(login_ui)
        QtCore.QMetaObject.connectSlotsByName(login_ui)

    def retranslateUi(self, login_ui):
        _translate = QtCore.QCoreApplication.translate
        login_ui.setWindowTitle(_translate("login_ui", "MainWindow"))
        self.label.setText(_translate("login_ui", "账户"))
        self.label_2.setText(_translate("login_ui", "密码"))
        self.label_3.setText(_translate("login_ui", "登录"))
        self.label_4.setText(_translate("login_ui", "注册"))
        self.label_5.setText(_translate("login_ui", "西邮人脸考勤系统"))
        self.label_6.setText(_translate("login_ui", "---作者：尹攀"))
